version: "3.8"

services:
  database:
    container_name: database
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "1338:5432"
    volumes:
      - pg:/var/lib/postgresql
volumes:
  pg: